import { StyleSheet } from 'react-native';
import { T } from './theme';

export const styles = StyleSheet.create({
  // ── Boot ──────────────────────────────────────────────────────────────────
  bootScreen:  { flex: 1, backgroundColor: T.bg, justifyContent: 'center', alignItems: 'center' },

  // ── Auth ──────────────────────────────────────────────────────────────────
  authContainer:     { flex: 1 },
  authBg:            { flex: 1 },
  authSpacer:        { height: 200 },
  authKeyboard:      { flex: 1 },
  authCard:          { flex: 1, backgroundColor: 'rgba(250,247,241,0.97)', borderTopLeftRadius: 28, borderTopRightRadius: 28, overflow: 'hidden' },
  authInner:         { padding: 28, paddingBottom: 24, flexGrow: 1 },
  authBottomSpacer:  { height: 80, backgroundColor: 'rgba(250,247,241,0.97)' },
  authLogoWrap:      { width: 64, height: 64, borderRadius: 32, backgroundColor: T.greenFaint, borderWidth: 1, borderColor: T.greenDark, justifyContent: 'center', alignItems: 'center', alignSelf: 'center', marginBottom: 16 },
  authTitle:         { color: T.textPri, fontSize: 26, fontWeight: '800', textAlign: 'center', letterSpacing: -0.5 },
  authSub:           { color: T.textMuted, fontSize: 13, textAlign: 'center', marginTop: 4, marginBottom: 28 },
  authTabs:          { flexDirection: 'row', backgroundColor: T.surface, borderRadius: 12, padding: 4, marginBottom: 20, borderWidth: 1, borderColor: T.cardBorder },
  authTab:           { flex: 1, paddingVertical: 10, borderRadius: 9, alignItems: 'center' },
  authTabActive:     { backgroundColor: T.greenDark },
  authTabText:       { color: T.textMuted, fontWeight: '600', fontSize: 14 },
  authTabTextActive: { color: '#fdfbf7' },
  authForm:          { gap: 12 },
  input:             { backgroundColor: T.surface, borderRadius: 14, padding: 16, color: T.textPri, fontSize: 16, borderWidth: 1, borderColor: T.cardBorder },
  roleRow:           { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginTop: 4 },
  roleLabel:         { color: T.textSec, fontSize: 13 },
  roleBtn:           { paddingHorizontal: 16, paddingVertical: 9, borderRadius: 22, borderWidth: 1, borderColor: T.cardBorder },
  roleBtnActive:     { backgroundColor: T.greenFaint, borderColor: T.green },
  roleBtnText:       { color: T.textMuted, fontSize: 13, fontWeight: '600' },
  roleBtnTextActive: { color: T.green },
  authError:         { color: '#b91c1c', fontSize: 13, textAlign: 'center' },
  authSubmit:        { backgroundColor: T.greenDark, padding: 16, borderRadius: 14, alignItems: 'center', marginTop: 8, height: 54, justifyContent: 'center', borderWidth: 1, borderColor: T.green },
  authSubmitText:    { color: '#fdfbf7', fontWeight: '700', fontSize: 16, letterSpacing: 0.3 },
  seedHint:          { marginTop: 20, gap: 5, paddingTop: 16, borderTopWidth: 1, borderTopColor: T.cardBorder },
  seedText:          { color: T.textMuted, fontSize: 11, textAlign: 'center' },

  // ── Layout principal ──────────────────────────────────────────────────────
  container:      { flex: 1, backgroundColor: T.bg },
  header:         { paddingHorizontal: 20, paddingTop: 54, paddingBottom: 14,
                    borderBottomWidth: 1, borderBottomColor: T.cardBorder,
                    shadowColor: '#2b2520', shadowOpacity: 0.08, shadowRadius: 8, shadowOffset: { width: 0, height: 3 },
                    elevation: 4, zIndex: 10 },
  headerDriver:   { backgroundColor: T.headerDriver },
  headerOwner:    { backgroundColor: T.headerOwner },
  headerTop:      { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle:    { color: T.textPri, fontSize: 20, fontWeight: '700', letterSpacing: -0.3 },
  headerSub:      { color: T.textMuted, fontSize: 12, marginTop: 2 },
  userBadge:      { width: 34, height: 34, borderRadius: 17, backgroundColor: T.charging, justifyContent: 'center', alignItems: 'center' },
  userBadgeOwner: { backgroundColor: T.greenDark },
  userInitial:    { color: '#fdfbf7', fontWeight: '700', fontSize: 15 },
  rolePill:       { alignSelf: 'flex-start', marginTop: 10, backgroundColor: 'rgba(43,37,32,0.05)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(43,37,32,0.05)' },
  rolePillText:   { color: T.textMuted, fontSize: 11, fontWeight: '600', letterSpacing: 0.5 },
  statsRow:       { flexDirection: 'row', gap: 8, marginTop: 10 },
  statPill:       { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: 'rgba(43,37,32,0.05)', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20 },
  statDot:        { width: 6, height: 6, borderRadius: 3 },
  statText:       { color: T.textPri, fontSize: 11, fontWeight: '600' },
  searchBar:      { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(43,37,32,0.05)', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 9, marginTop: 10, borderWidth: 1, borderColor: 'rgba(43,37,32,0.10)' },
  searchInput:    { flex: 1, color: T.textPri, fontSize: 13, padding: 0 },
  serverError:    { color: '#b91c1c', fontSize: 11, marginTop: 6 },
  lastUpdate:     { color: T.textMuted, fontSize: 10, marginTop: 3 },

  // ── Tabs ──────────────────────────────────────────────────────────────────
  tabs:          { flexDirection: 'row', marginTop: 14 },
  tabBtn:        { flex: 1, paddingVertical: 11, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive:     { borderBottomColor: T.green },
  tabText:       { color: T.textMuted, fontWeight: '600', fontSize: 13 },
  tabTextActive: { color: T.green },

  // ── Tarjetas ──────────────────────────────────────────────────────────────
  list:       { padding: 14, gap: 10, paddingBottom: 76 },
  card:       { backgroundColor: T.card, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: T.cardBorder },
  cardMine:   { borderColor: T.green, borderWidth: 1.5 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  dot:        { width: 8, height: 8, borderRadius: 4 },
  chargerId:  { color: T.textPri, fontWeight: '700', fontSize: 15, flex: 1, letterSpacing: 0.3 },
  ownerBadge: { backgroundColor: T.surface, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, borderWidth: 1, borderColor: T.cardBorder },
  ownerText:  { color: T.textMuted, fontSize: 11 },
  mineBadge:  { backgroundColor: T.greenFaint, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, borderWidth: 1, borderColor: T.greenDark },
  mineText:   { color: T.green, fontSize: 11, fontWeight: '700' },
  location:   { color: T.textMuted, fontSize: 13, marginBottom: 10, marginLeft: 16 },
  statusRow:  { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 6 },
  statusText: { fontWeight: '700', fontSize: 13 },
  txText:     { color: T.textMuted, fontSize: 11 },

  // ── Specs ─────────────────────────────────────────────────────────────────
  specsRow:       { flexDirection: 'row', gap: 6, flexWrap: 'wrap', marginBottom: 10 },
  specChip:       { backgroundColor: T.surface, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, borderWidth: 1, borderColor: T.cardBorder },
  specText:       { color: T.textSec, fontSize: 11, fontWeight: '700' },
  specChipPrice:  { backgroundColor: T.greenFaint, borderColor: T.greenDark },
  specTextPrice:  { color: T.greenLight },

  // Chips técnicos en tarjeta de dueño
  techChip:      { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: T.surface,
    borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, borderWidth: 1, borderColor: T.cardBorder },
  techChipText:  { color: T.textSec, fontSize: 11, fontWeight: '600' },

  // ── Sesión activa ─────────────────────────────────────────────────────────
  sessionBox:   { backgroundColor: T.bg, borderRadius: 12, padding: 14, marginBottom: 10, gap: 8, borderWidth: 1, borderColor: T.cardBorder },
  sessionRow:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sessionLabel: { color: T.textMuted, fontSize: 12 },
  sessionValue: { color: T.textPri, fontSize: 13, fontWeight: '600' },
  sessionCost:  { color: T.green, fontSize: 15, fontWeight: '800' },

  // ── Botones ───────────────────────────────────────────────────────────────
  btn:         { marginTop: 12, paddingVertical: 14, borderRadius: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8 },
  btnStart:    { backgroundColor: T.greenDark, borderWidth: 1.5, borderColor: T.green },
  btnDirections: { backgroundColor: T.greenFaint, borderWidth: 1.5, borderColor: T.greenLight },
  btnStop:     { backgroundColor: '#fbe7e7', borderWidth: 1.5, borderColor: '#b91c1c' },
  btnReserve:  { backgroundColor: T.surface, borderWidth: 1, borderColor: T.cardBorder },
  btnText:     { color: '#fdfbf7', fontWeight: '700', fontSize: 15, letterSpacing: 0.2 },

  // ── Píldora de sesión activa (flotante) ──────────────────────────────────
  sessionPill:      {
    position: 'absolute', bottom: 90, left: 16, right: 16,
    backgroundColor: T.chargingBg,
    borderRadius: 20, padding: 14, paddingHorizontal: 16,
    flexDirection: 'row', alignItems: 'center', gap: 12,
    borderWidth: 1.5, borderColor: T.charging,
    shadowColor: T.charging, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.35, shadowRadius: 12,
    elevation: 8,
  },
  sessionPillDot:  {
    width: 10, height: 10, borderRadius: 5,
    backgroundColor: T.charging,
    shadowColor: T.charging, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 1, shadowRadius: 6,
  },
  sessionPillTitle: { color: T.textPri, fontWeight: '700', fontSize: 14 },
  sessionPillId:    { color: T.charging, fontWeight: '600', fontSize: 13, opacity: 0.9 },
  sessionPillStat:  { color: T.textMuted, fontSize: 12 },
  sessionPillStop:  { backgroundColor: '#fbe7e7', borderRadius: 10, padding: 8, borderWidth: 1, borderColor: '#b91c1c' },

  // ── Modals ────────────────────────────────────────────────────────────────
  modalOverlay:    { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end', zIndex: 100, elevation: 100 },
  modal:           { backgroundColor: T.card, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 24, paddingBottom: 100, borderTopWidth: 1, borderTopColor: T.cardBorder },
  modalTitle:      { color: T.textPri, fontWeight: '800', fontSize: 20, marginBottom: 4 },
  modalActions:    { flexDirection: 'row', gap: 10, marginTop: 20 },
  btnSecondary:    { backgroundColor: 'rgba(43,37,32,0.05)', borderWidth: 1, borderColor: 'rgba(43,37,32,0.15)' },

  qrFrame:         { width: 200, height: 200, borderWidth: 2, borderColor: T.green, borderRadius: 16, justifyContent: 'center', alignItems: 'center', backgroundColor: T.surface, marginBottom: 16 },
  listHint:        { color: T.textMuted, fontSize: 11, marginTop: 8, textAlign: 'center' },
  methodRow:       { flexDirection: 'row', alignItems: 'center', backgroundColor: T.surface, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: T.cardBorder },
  methodDisplay:   { color: T.textPri, fontWeight: '600', fontSize: 14 },
  methodDefault:   { color: T.green, fontSize: 11, marginTop: 2 },

  // ── Pantalla sesión activa ────────────────────────────────────────────────
  sessionScreen:    { flex: 1, padding: 24, justifyContent: 'center', gap: 24 },
  sessionKwhBox:    { alignItems: 'center', paddingVertical: 32, backgroundColor: T.card, borderRadius: 24, borderWidth: 1, borderColor: T.cardBorder },
  sessionKwhLabel:  { color: T.textMuted, fontSize: 12, fontWeight: '600', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 8 },
  sessionKwhValue:  { color: T.green, fontSize: 64, fontWeight: '800', letterSpacing: -2 },
  sessionKwhUnit:   { color: T.textSec, fontSize: 28, fontWeight: '600' },
  sessionDivider:   { height: 1, backgroundColor: T.cardBorder },
  sessionStats:     { flexDirection: 'row', backgroundColor: T.card, borderRadius: 20, borderWidth: 1, borderColor: T.cardBorder, padding: 20 },
  sessionStat:      { flex: 1, alignItems: 'center' },
  sessionStatVal:   { color: T.textPri, fontSize: 20, fontWeight: '800', letterSpacing: -0.5 },
  sessionStatLbl:   { color: T.textMuted, fontSize: 11, marginTop: 4 },
  sessionStatSep:   { width: 1, backgroundColor: T.cardBorder },
  sessionPriceNote: { color: T.textMuted, fontSize: 12, textAlign: 'center' },
  sessionPulse:     { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  sessionPulseText: { color: T.textMuted, fontSize: 12 },
  sessionStopBtn:   { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, backgroundColor: '#fbe7e7', borderRadius: 16, padding: 18, borderWidth: 1, borderColor: '#b91c1c' },
  sessionStopText:  { color: T.dangerText, fontWeight: '700', fontSize: 17 },

  // ── Empty state ───────────────────────────────────────────────────────────
  empty:     { alignItems: 'center', paddingTop: 80, paddingHorizontal: 32 },
  emptyText: { color: T.textSec, fontSize: 16, fontWeight: '600' },
  emptyHint: { color: T.textMuted, fontSize: 13, marginTop: 6, textAlign: 'center' },

  // ── Negocio ───────────────────────────────────────────────────────────────
  sectionTitle:       { color: T.textMuted, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.5, marginTop: 12, marginBottom: 6 },
  earningsCard:       { backgroundColor: T.greenFaint, borderRadius: 16, padding: 22, marginBottom: 8, borderWidth: 1, borderColor: T.greenDark },
  earningsTitle:      { color: T.textSec, fontSize: 12, fontWeight: '600', marginBottom: 6, letterSpacing: 0.5 },
  earningsAmount:     { color: T.green, fontSize: 36, fontWeight: '800', marginBottom: 16, letterSpacing: -1 },
  earningsRow:        { flexDirection: 'row', justifyContent: 'space-between' },
  earningsStat:       { alignItems: 'center' },
  earningsStatVal:    { color: T.textPri, fontSize: 18, fontWeight: '700' },
  earningsStatLbl:    { color: T.textMuted, fontSize: 11, marginTop: 3 },
  priceRow:           { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10, backgroundColor: T.bg, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: T.cardBorder },
  priceLabel:         { color: T.textMuted, fontSize: 11, fontWeight: '600', letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 3 },
  priceValue:         { color: T.textPri, fontSize: 15, fontWeight: '700' },
  priceUserNote:      { color: T.textMuted, fontSize: 11, marginTop: 3 },
  priceEdit:          { color: T.green, fontWeight: '600', fontSize: 13 },

  plCard:    { backgroundColor: T.card, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: T.cardBorder, marginBottom: 8 },
  plRow:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: T.cardBorder },
  plLabel:   { color: T.textMuted, fontSize: 13 },
  plPos:     { color: T.green, fontWeight: '700', fontSize: 13 },
  plNeg:     { color: '#b91c1c', fontWeight: '700', fontSize: 13 },
  plTotal:   { borderBottomWidth: 0, marginTop: 4 },
  plTotalLabel: { color: T.textPri, fontWeight: '700', fontSize: 15 },
  plTotalVal:   { color: T.green, fontWeight: '800', fontSize: 17 },
  plNote:    { color: T.textMuted, fontSize: 11, marginTop: 12, lineHeight: 16 },
  priceEditor:        { flexDirection: 'row', alignItems: 'center', marginTop: 10, gap: 8 },
  priceInput:         { flex: 1, backgroundColor: T.bg, borderRadius: 10, padding: 12, color: T.textPri, fontSize: 15, borderWidth: 1.5, borderColor: T.green },
  priceUnit:          { color: T.textMuted, fontSize: 12 },
  priceSave:          { backgroundColor: T.greenDark, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10 },
  priceSaveText:      { color: T.textPri, fontWeight: '700', fontSize: 13 },
  priceCancel:        { padding: 10 },
  sessionHistCard:    { backgroundColor: T.card, borderRadius: 14, padding: 14, marginBottom: 8, borderWidth: 1, borderColor: T.cardBorder },
  sessionHistHeader:  { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  sessionHistId:      { color: T.textPri, fontWeight: '700', fontSize: 14 },
  sessionHistRevenue: { color: T.green, fontWeight: '800', fontSize: 14 },
  sessionHistLocation:{ color: T.textMuted, fontSize: 12, marginBottom: 8 },
  sessionHistRow:     { flexDirection: 'row', gap: 12 },
  sessionHistDetail:  { color: T.textMuted, fontSize: 12 },

  // ── Mapa ──────────────────────────────────────────────────────────────────
  map:              { flex: 1 },
  mapPin:           { width: 36, height: 36, borderRadius: 18, borderWidth: 3, backgroundColor: '#1a1710', justifyContent: 'center', alignItems: 'center',
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.4, shadowRadius: 4, elevation: 5 },
  mapPinSelected:   { width: 44, height: 44, borderRadius: 22, borderWidth: 3.5 },
  mapPinDot:        { width: 14, height: 14, borderRadius: 7, position: 'absolute' },
  mapPinMark:       { width: 9, height: 9, borderRadius: 5, backgroundColor: T.green, position: 'absolute', top: -2, right: -2 },

  // ── Selector de ubicación ─────────────────────────────────────────────────
  locPickerPin:       { position: 'absolute', top: '50%', left: '50%',
    transform: [{ translateX: -19 }, { translateY: -42 }], alignItems: 'center', zIndex: 10 },
  locPickerShadow:    { width: 12, height: 6, borderRadius: 6, backgroundColor: 'rgba(0,0,0,0.25)', marginTop: 2 },
  locPickerTopCard:   {
    position: 'absolute', top: 56, left: 16, right: 16,
    backgroundColor: 'rgba(255,255,255,0.95)', borderRadius: 14, padding: 12,
    flexDirection: 'row', alignItems: 'center', gap: 8,
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 6, elevation: 4,
  },
  locPickerBottomCard:{ position: 'absolute', bottom: 0, left: 0, right: 0,
    backgroundColor: T.card, borderTopLeftRadius: 24, borderTopRightRadius: 24,
    padding: 20, paddingBottom: 36, borderTopWidth: 1, borderTopColor: T.cardBorder,
    shadowColor: '#000', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.3, shadowRadius: 10, elevation: 8,
  },

  // ── Mapa — burbujas de marcadores (estilo Airbnb) ────────────────────────
  mapBubble:        {
    borderRadius: 22, paddingHorizontal: 12, paddingVertical: 8,
    flexDirection: 'row', alignItems: 'center', gap: 5,
    shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.28, shadowRadius: 6,
    elevation: 6,
  },
  mapBubbleStatusDot: { width: 7, height: 7, borderRadius: 4 },
  mapBubbleTip:     {
    width: 0, height: 0, backgroundColor: 'transparent', borderStyle: 'solid',
    borderLeftWidth: 5, borderRightWidth: 5, borderTopWidth: 7,
    borderLeftColor: 'transparent', borderRightColor: 'transparent',
    marginTop: -1,
  },

  // ── Mapa — buscador flotante ──────────────────────────────────────────────
  mapSearchWrap:    { position: 'absolute', top: 14, left: 14, right: 14, zIndex: 200 },
  mapSearchBox:     {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#ffffff', borderRadius: 14,
    paddingHorizontal: 14, paddingVertical: 11,
    shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.15, shadowRadius: 8,
    elevation: 8,
  },
  mapSearchInput:   { flex: 1, fontSize: 15, color: '#2b2520', padding: 0 },
  mapSearchDropdown:{ backgroundColor: '#ffffff', borderRadius: 14, marginTop: 6, overflow: 'hidden',
    shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.12, shadowRadius: 8, elevation: 6 },
  mapSearchItem:    { flexDirection: 'row', alignItems: 'center', padding: 14, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  mapSearchItemId:  { color: '#2b2520', fontWeight: '700', fontSize: 14 },
  mapSearchItemLoc: { color: '#94866f', fontSize: 12, marginTop: 1 },
  mapSearchItemPrice:{ color: T.green, fontSize: 12, fontWeight: '700' },

  // ── Mapa — botón flotante "cargador más cercano" ──────────────────────────
  nearestFab:       {
    position: 'absolute', bottom: 80, right: 16,
    width: 54, height: 54, borderRadius: 27,
    backgroundColor: T.greenDark, borderWidth: 1.5, borderColor: T.green,
    alignItems: 'center', justifyContent: 'center',
    shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.25, shadowRadius: 8,
    elevation: 8, zIndex: 90,
  },

  // ── Mapa — tira de cargadores ─────────────────────────────────────────────
  mapStrip:         { position: 'absolute', bottom: 70, left: 0, right: 0, zIndex: 100 },
  mapStripCard:     {
    backgroundColor: T.card, borderRadius: 16, padding: 14, width: 180,
    borderWidth: 1, borderColor: T.cardBorder,
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 6,
    elevation: 5,
  },
  mapStripId:       { color: T.textPri, fontWeight: '700', fontSize: 13 },
  mapStripLocation: { color: T.textMuted, fontSize: 12, marginBottom: 4 },
  mapStripPrice:    { color: T.green, fontWeight: '800', fontSize: 14 },
  mapStripChip:     { backgroundColor: T.surface, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, borderWidth: 1, borderColor: T.cardBorder },
  mapStripChipText: { color: T.textSec, fontSize: 10, fontWeight: '700' },

  mapPanel:         { position: 'absolute', bottom: 62, left: 0, right: 0, backgroundColor: T.card, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 24, borderTopWidth: 1, borderTopColor: T.cardBorder, elevation: 30, shadowColor: '#000', shadowOffset: { width: 0, height: -6 }, shadowOpacity: 0.5, shadowRadius: 16, zIndex: 100 },

  bottomBar:        { position: 'absolute', bottom: 0, left: 0, right: 0, height: 62, backgroundColor: T.surface, borderTopWidth: 1, borderTopColor: T.cardBorder, flexDirection: 'row', elevation: 20, zIndex: 50 },
  bottomTab:        { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 },
  bottomTabLabel:   { color: T.textMuted, fontSize: 10, fontWeight: '600' },
  bottomTabLabelActive: { color: T.greenLight },
  mapPanelHandle:   { width: 36, height: 4, backgroundColor: T.cardBorder, borderRadius: 2, alignSelf: 'center', marginBottom: 16 },
  mapPanelHeader:   { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
  mapPanelId:       { color: T.textPri, fontWeight: '800', fontSize: 16, letterSpacing: 0.3 },
  mapPanelLocation: { color: T.textMuted, fontSize: 13, marginTop: 3 },
  mapPanelPrice:    { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: T.surface, borderRadius: 12, padding: 14, marginBottom: 14, borderWidth: 1, borderColor: T.cardBorder },
  mapPanelPriceVal: { color: T.green, fontSize: 18, fontWeight: '800' },
  mapPanelPriceNote:{ color: T.textMuted, fontSize: 11, marginTop: 3 },
  mapPanelActions:  { flexDirection: 'row', gap: 10 },
  btnReserve:       { borderWidth: 1.5, borderColor: T.greenDark, backgroundColor: T.greenFaint },
  callout:          { backgroundColor: T.card, borderRadius: 12, padding: 14, minWidth: 180, borderWidth: 1, borderColor: T.cardBorder },
  calloutMine:      { borderColor: T.green },
  calloutId:        { color: T.textPri, fontWeight: '700', fontSize: 14 },
  calloutMineBadge: { backgroundColor: T.greenFaint, color: T.green, fontSize: 10, fontWeight: '700', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  calloutLocation:  { color: T.textMuted, fontSize: 12, marginBottom: 6 },
  calloutStatus:    { fontWeight: '700', fontSize: 13, marginBottom: 4 },
  calloutSpec:      { color: T.textSec, fontSize: 11, backgroundColor: T.surface, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  calloutKwh:       { color: T.green, fontSize: 12, marginTop: 6, fontWeight: '700' },
  calloutOwner:     { color: T.textMuted, fontSize: 11, marginTop: 6 },
});
